# -*- coding: utf-8 -*-
"""Primeiro Data Science.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/15z5s-ki-E5-AVmeXgOFOaLWj--d6_76j

#Analise da dataset <font color='blue'>**MovieLens**</font>

A base de dados utilizada será utilizada é a <font color='blue'>**ml-latest-small**</font>

---

```
Importando a biblioteca pandas e visualizando uma amostra do data frame
```
"""

import pandas as pd

notas = pd.read_csv('ratings.csv')
notas.head()

"""```
Traduzindo os cabeçalhos das colunas.
```
"""

notas.columns = ['usuarioId','filmeID','nota','momento']

 notas.head()

"""```
Visualizar as notas únicas dentro do data frame.
```
"""

notas.nota.unique()

"""```
Visualizar as frequências das notas
```
"""

notas.nota.value_counts()

"""```
melhorando a visualização dos valores de frequência 
```
"""

notas.nota.plot(kind='hist')

"""```
Obter a média e a medianda das notas
```
"""

print(f'A media das notas é {notas.nota.mean()}')
print(f'A mediana das notas é de {notas.nota.median()}')

"""```
Trazendo informações mais completas
```
"""

notas.nota.describe()

"""```
Melhorando a visualização 

importando a biblioteca seaborn e visualizando dados com grafico boxplot
```
"""

import seaborn as sns

sns.boxplot(notas.nota)

"""```
Importando o arquico de filmes
```
"""

filmes = pd.read_csv('movies.csv')
filmes.head()

"""```
Traduzindo o o título das colunas
```
"""

filmes.columns = ['filmeId','titulo','genero']
filmes.head()

"""```
Obtendo a media de notas de Toy Story e Jumanji
```
"""

print(f'Media do filme Toy Story é {notas.query("filmeID == 1").mean().nota:}')
print(f'Média do filme Jumaji é {notas.query("filmeID == 2").mean().nota}')

"""```
Obtendo média de todos os filmes
```
"""

media_de_notas = notas.groupby("filmeID").mean().nota
media_de_notas

"""Distribuição das medias de notas dos filmes"""

media_de_notas.plot(kind = 'hist')

media_de_notas.describe()

"""```
Importanto a biblioteca matplotlib para melhorarar a experiencia com os gráficos
```
"""

import matplotlib.pyplot as plt

plt.figure(figsize=(7,8))
plt.title('Distribuição de medias')
sns.boxplot(y = media_de_notas)

plt.figure(figsize=(7,8))
sns.distplot(media_de_notas, bins=15)

tmdb = pd.read_csv('tmdb_5000_movies.csv')
tmdb.head()

tmdb.original_language.unique()

"""```
Visualizar qual é a nota única
```
"""

tmdb.vote_average.unique()